import { AlertTriangle, Shield, Stethoscope, FileText } from 'lucide-react';

export default function MedicalDisclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-blue-50 py-12 px-4 sm:py-16">
      <div className="max-w-4xl mx-auto">
        {/* Header Card */}
        <div className="bg-white rounded-2xl shadow-lg p-8 mb-6 border-t-4 border-blue-600">
          <div className="flex items-center gap-3 mb-6">
            <div className="bg-blue-100 p-3 rounded-lg">
              <FileText className="w-8 h-8 text-blue-600" />
            </div>
            <h1 className="text-3xl font-bold text-gray-900">Medical Disclaimer</h1>
          </div>
          
          <div className="prose prose-slate max-w-none">
            <p className="text-lg text-gray-700 leading-relaxed">
              NeuroSense AI is a research and screening support tool designed to assist
              in analyzing handwriting and drawing patterns using artificial intelligence.
            </p>
          </div>
        </div>

        {/* Warning Card */}
        <div className="bg-gradient-to-r from-red-50 to-orange-50 rounded-2xl shadow-lg p-8 mb-6 border-l-4 border-red-500">
          <div className="flex items-start gap-4">
            <div className="bg-red-100 p-3 rounded-lg flex-shrink-0">
              <AlertTriangle className="w-7 h-7 text-red-600" />
            </div>
            <div>
              <h2 className="text-xl font-bold text-red-900 mb-2">Important Notice</h2>
              <p className="text-lg font-semibold text-red-700 leading-relaxed">
                This system does NOT provide medical diagnosis, treatment, or medical advice.
              </p>
            </div>
          </div>
        </div>

        {/* Information Cards */}
        <div className="grid md:grid-cols-2 gap-6">
          {/* Not a Substitute Card */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow duration-300">
            <div className="flex items-start gap-3 mb-3">
              <div className="bg-amber-100 p-2 rounded-lg">
                <Shield className="w-6 h-6 text-amber-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900">Not a Substitute</h3>
            </div>
            <p className="text-gray-600 leading-relaxed">
              Results generated by this platform should not be interpreted as a substitute
              for professional medical evaluation, diagnosis, or treatment.
            </p>
          </div>

          {/* Professional Advice Card */}
          <div className="bg-white rounded-xl shadow-md p-6 hover:shadow-lg transition-shadow duration-300">
            <div className="flex items-start gap-3 mb-3">
              <div className="bg-green-100 p-2 rounded-lg">
                <Stethoscope className="w-6 h-6 text-green-600" />
              </div>
              <h3 className="text-lg font-semibold text-gray-900">Seek Professional Advice</h3>
            </div>
            <p className="text-gray-600 leading-relaxed">
              Always seek the advice of a qualified healthcare provider regarding any
              medical condition or health concerns.
            </p>
          </div>
        </div>

        {/* Footer Note */}
        <div className="mt-8 bg-slate-100 rounded-xl p-6 border border-slate-200">
          <p className="text-sm text-slate-600 text-center leading-relaxed">
            By using NeuroSense AI, you acknowledge that you understand this disclaimer and agree that
            the platform is intended for research and screening support purposes only. All decisions
            regarding medical care should be made in consultation with qualified healthcare professionals.
          </p>
        </div>
      </div>
    </div>
  );
}